# Generated by Django 5.1.1 on 2024-09-30 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField(default=20)),
                ('password', models.CharField(max_length=64)),
                ('data', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserInfofo',
        ),
    ]
