# Generated by Django 5.1.1 on 2024-09-30 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_userinfo_delete_userinfofo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='name',
            new_name='user',
        ),
    ]
